### PR TITLE
Feature/IJ-170 Login Redesign

### PR DESCRIPTION
**Pull request by garethdandrews**
Re-designed the login page for the platform as the original view was very overcrowded:

Screenshot from 2021-05-17 13-03-01

The root route has been changed to the User login page. The new design is a lot more concise and clean looking:

Screenshot from 2021-05-17 14-12-56

The extra links on the old login forms have been extracted out into a modal, accessed through the 'Trouble Signing In?' linkl.
Before:
Screenshot from 2021-05-17 13-05-39

After: 
Screenshot from 2021-05-17 12-58-16

By clicking 'Learn More', you will be redirected to the 'About' section, where you detailed descriptions of the project, Include and the Lab can be found:

Screenshot from 2021-05-17 12-57-55

The Team Member login is as follows. It can be found by clicking the link in the top right of User login. Similarly, you can navigate back to the User login by a link in the top right.

Screenshot from 2021-05-17 14-12-56

Mobile layout:
Screenshot from 2021-05-17 14-15-23

Screenshot from 2021-05-17 14-15-43

Currently, the only differences between the User login and the Team Member login are the Icons in the form title, and the fact that the User login has the big yellow brand card - making it more user friendly than the staff alternative.

If you have any thoughts or comments let me know!

### CODE REVIEW

**Comment by IeuanSkinner** [comment]
@garethdandrews; I made some minor style updates so the icons aren't repeated on the login screen.

Screenshot 2021-05-17 at 16 30 50

**Comment by IeuanSkinner** [comment]
@phil-6; Should we be running this by Include UK to see if they're happy with it? It makes much more logical to sense to me now and we styled the login form on the Facebook login form so hopefully there's identifiability for Users.

**Review by IeuanSkinner — APPROVED** [review]
LGTM

**Comment by garethdandrews** [comment]
> @garethdandrews; I made some minor style updates so the icons aren't repeated on the login screen.
> 
> Screenshot 2021-05-17 at 16 30 50

Looks good - I much prefer what you've done with the Team Member link :+1:

**Comment by phil-6** [comment]
Added a few style updates myself.
Mobile user login now has a header:
image

Only the crisis modal now has the orange sides, the devise modal now matches the login form background:
image
image

The buttons also no long have text-decoration underline on hover, and the buttons in the modal now change font colour on hover too.

I'm happy with this now. I don't think we need to run it past Include, merge away.

**Review by phil-6 — APPROVED** [review]

**Pull request merged**
