### PR TITLE
IJ-78 Design Updates

### PR DESCRIPTION
**Pull request by phil-6**
Pretty major but still subtle design overhaul. I've updated and tweaked almost all the styling throughout the app and I'm a lot happier with it now. 
I have a couple of different versions of the colours saved in the variables file to allow easy switching should include want. 

### Original
image

### New
image

### Original
image

### New
image

### Original
image

### New
image

### Original
image

### New
image

### Original
image

### New
image

### Original
image

### New
image

### Original
image

### New
image

### Original
image

### New
image

### Original
image

### New
image

### Original
image

### New
image

### Original
image

### New
image

### Original
image

### New
image

### Original
image

### New
image
image

### Original
image

### New
image

### Original
image

### New
image

### Original
image

### New
image

You get the idea.

I'm still expecting tweaks as we go along but is everyone happy with this?

### CODE REVIEW

**Comment by IeuanSkinner** [comment]
Conflicts will need resolving but this is looking much better, there's some little UI bugs like the icon wrapping on the mobile permissions screen but we're better off fixing that in future work and just getting this PR in a mergable state given the state of the conflicts.

**Comment by phil-6** [comment]
merge conflicts resolved :+1:

**Comment by IeuanSkinner** [comment]
@phil-6 why closed?

**Comment by phil-6** [comment]
@IeuanSkinner open again! :smile:

**Review by IeuanSkinner — APPROVED** [review]
LGTM

**Pull request merged**
