### PR TITLE
IJ 29 devise views

### PR DESCRIPTION
**Pull request by IeuanSkinner**
Updated all of the devise views to use a centered bootstrap form template that includes floating labels for the input fields and the Include UK colours for the buttons and links.

### CODE REVIEW

**Review by phil-6 — APPROVED** [review]
Some of the colours clash a little but this is an easy fix for later. Great work.

It looks as though there are some odd bugs with the unlocks controller but I think this can be resolved further down the line.

**Comment by IeuanSkinner** [comment]
> Some of the colours clash a little but this is an easy fix for later. Great work.
> 
> It looks as though there are some odd bugs with the unlocks controller but I think this can be resolved further down the line.

I'm only using their brand colours so not sure what clash could be occurring unless you're saying their brand colours clash which I'd disagree with.

**Comment by IeuanSkinner** [comment]
> Some of the colours clash a little but this is an easy fix for later. Great work.
> 
> It looks as though there are some odd bugs with the unlocks controller but I think this can be resolved further down the line.

For the unlocks controller have you dropped and created the DB with the latest changes? I also saw error messages from this before I'd merged the changes you'd put on master to enable the devise locking mechanism. 

With the changes those messages went aways and now on sign up you see 'uninitialized constant PagesController...' which is basically the result of some routing configurations that should get fixed via IJ-31

**Comment by phil-6** [comment]
> > Some of the colours clash a little but this is an easy fix for later. Great work.
> > It looks as though there are some odd bugs with the unlocks controller but I think this can be resolved further down the line.
> 
> I'm only using their brand colours so not sure what clash could be occurring unless you're saying their brand colours clash which I'd disagree with.

The link blue and the alert red don't work well on such a dark background.

**Pull request merged**
